---

- hosts: swarm
  become: True
  roles:
    - docker

- hosts: swarm-manager
  become: True
  roles:
    - role: 'swarm'
      swarm_type_of_node: 'front'
      swarm_manager_address: "{{ hostvars[groups['swarm-manager'][0]]['ansible_default_ipv4']['address'] }}"

- hosts: swarm-worker
  become: True
  roles:
    - role: 'swarm'
      swarm_type_of_node: 'wn'
      swarm_manager_address: "{{ hostvars[groups['swarm-manager'][0]]['ansible_default_ipv4']['address'] }}"
